import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResponsiveNavbar from "@/components/Navbar";
import LowtownFooter from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["Poppins"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["Manrope"],
});

export const metadata = {
  title: "Glassmate Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" webcrx="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-gray-100 font-poppins`}
      >
        <ResponsiveNavbar />
        {children}
        <LowtownFooter />
        <WhatsAppButton
          phoneNumber="+919987703344" // Replace with your actual number
          message="Hello! I saw your website and I'm interested in your services. Can we chat?"
        />
      </body>
    </html>
  );
}
