import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import ResponsiveNavbar from "@/components/Navbar";
import LowtownFooter from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";

const geistSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["Manrope"],
// });

export const metadata = {
  title: "Glassmate Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" webcrx="">
      <body
        className={`${geistSans.variable} antialiased bg-gray-900 text-gray-100 font-poppins`}
      >
        <ResponsiveNavbar />
        {children}
        <LowtownFooter />
        <WhatsAppButton
          phoneNumber="+918097803740" // Replace with your actual number
          message="Hey! Just saw your website liked the vibe!I&apos;m curious to know how GlassMate can help tell my brand&apos;s story. Shall we chat?"
        />
      </body>
    </html>
  );
}
